version: '3.7'
services:
  os:
    build: ./docker/centos
    ports:
      - '${WEB_HTTP_PORT}:80'
      - '${WEB_HTTPS_PORT}:443'
    volumes:
      - ${SOURCE_PATH}:/var/www/html
      - ${LOGS_PATH}:/var/log/httpd
    restart: always